### ISSUE TITLE
Doesn't work : selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" role="submit" color="yellow" class="button button--fluid large button--yellow">...</button> is not clickable at point (460, 270). Other element would receive the click: <div class="dimmer" data-qa="loading spinner">...</div>

### ISSUE THREAD

**Issue by sabujp** [daveharmon/Southwest-Checkin#13]
Got it started, but at check in time it blew up with this error :

> Waiting for checkin time 2018-01-06 07:00:00. Time now is: 2018-01-06 06:59:49.194967. Waiting 5s.
> checking in...
> loading...
> loading...
> loading...
> loading...
> loading...
> loading...
> error displayed, trying again
> no error displayed, moving on!
> confirming check in...
> Traceback (most recent call last):
>   File "southwest_checkin.py", line 111, in <module>
>     submit.click()
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 77, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 494, in _execute
>     return self._parent.execute(command, params)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" role="submit" color="yellow" class="button button--fluid large button--yellow">...</button> is not clickable at point (460, 270). Other element would receive the click: <div class="dimmer" data-qa="loading spinner">...</div>
>   (Session info: chrome=63.0.3239.59)
>   (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.10.10-041010-generic x86_64)

**Comment by colacadstink** [comment]
I think I've got a fix for this, but I can't check for sure unless I've got a flight to test it against. Pull a copy of my fork, and see if it works for you: https://github.com/colacadstink/Southwest-Checkin

**Comment by sabujp** [comment]
k, but is daveharmon not taking any pr's or working on this anymore? Are you the new maintainer?

**Comment by sabujp** [comment]
my next sw flight isn't until mid July 2018, maybe someone else can test your fork before me

**Comment by daveharmon** [comment]
I still take PRs, i think he was just saying he didn't have a way to test his pr before making it. unfortunately this project doesn't really lend itself to natural unit testing or anything of the sort

i have a flight later this week and am planning to test your fix @colacadstink 
I'll let you know how that goes

**Comment by daveharmon** [comment]
I actually didn't even get past the first screen. I think we need to have the submit button behind a try statement, but needed to secure a boarding position to put my luggage in the overhead bin and couldn't test that theory.

**Comment by daveharmon** [comment]
> Waiting for checkin time 2018-02-18 17:30:00. Time now is: 2018-02-18 17:29:51.533548. Waiting 5s.
checking in...
no error displayed, moving on!
confirming check in...
loading done
checked in - getting boarding position
Traceback (most recent call last):
  File "southwest_checkin.py", line 128, in <module>
    boardingPositionDiv = driver.find_element_by_class_name("boarding-group-and-position")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 415, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 756, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"boarding-group-and-position"}
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.12.5 x86_64)
